// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Bookva.DAL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AuthorChangedDateOfBirthType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuthorChangedDateOfBirthType));
        
        string IMigrationMetadata.Id
        {
            get { return "201603122023581_Author-ChangedDateOfBirthType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
