// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Bookva.DAL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WorkChangedDateType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkChangedDateType));
        
        string IMigrationMetadata.Id
        {
            get { return "201603131028260_Work-ChangedDateType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
